services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    